export const FETCH_JEWELLERIES_SUCCESS = 'FETCH_JEWELLERIES_SUCCESS';
export const ADD_JEWELLERY_SUCCESS = 'ADD_JEWELLERY_SUCCESS';
export const REMOVE_JEWELLERY_SUCCESS = 'REMOVE_JEWELLERY_SUCCESS';
export const UPDATE_JEWELLERY_SUCCESS = 'UPDATE_JEWELLERY_SUCCESS';