export default [
  {
    name: 'Anchiale',
    type: 'rings',
    gender: 'female',
    category: 'vow',
    description: 'An exquisite symbol of your marriage commitment, this diamond wedding band is sure to please. Crafted in two-toned gold, this squared-top ring is set with a single round-cut diamond solitaire. A thoughtful symbol of your love, this majestic ring is finished with a bright polished luster.',
    price: '$940.00',
    metalType: '18K',
    goldWeight: '5.00g',
    stoneInfo: '1 Diamond-0.050cts',
    productCode: 'LMR00037'
  },
  {
    name: 'Anchiale',
    type: 'rings',
    gender: 'male',
    category: 'vow',
    description: 'An exquisite symbol of your marriage commitment, this diamond wedding band is sure to please. Crafted in two-toned gold, this squared-top ring is set with a single round-cut diamond solitaire. A thoughtful symbol of your love, this majestic ring is finished with a bright polished luster.',
    price: '$1270.00',
    metalType: '18K',
    goldWeight: '7.05g',
    stoneInfo: '1 Diamond-0.085cts',
    productCode: 'LMR00036'
  },
  {
    name: 'Arc',
    type: 'rings',
    category: 'heritage',
    description: 'The Goddess of Rainbow. Let your love shine just a bit brighter with the clean and classic look of the rainbow. The solitaire diamond center sits atop a classic band, decorated the trademark Lovemark Diamond beading on the outer band.',
    price: '$1300.00',
    metalType: '18K',
    goldWeight: '2.74g',
    stoneInfo: '1 Diamond-0.185cts, 1 Diamond-0.007cts',
    productCode: 'LMR00004'
  },
  {
    name: 'Arrow',
    type: 'rings',
    category: 'citylights',
    price: '$360.00',
    metalType: '18K',
    goldWeight: '1.46g',
    stoneInfo: '22 Yellow Diamonds-0.075cts',
    productCode: 'LMR00010'
  },
  {
    name: 'Arrow Round',
    type: 'rings',
    category: 'citylights',
    price: '$400.00',
    metalType: '18K',
    goldWeight: '1.44g',
    stoneInfo: '28 Yellow Diamonds-0.072cts',
    productCode: 'LMR00009'
  },
  {
    name: 'BAND IN 18K TWO TONE',
    type: 'rings',
    gender: 'male',
    category: 'vow',
    price: '$1,060.00',
    metalType: '18K',
    goldWeight: '7.00g',
    stoneInfo: '8 Diamonds-0.043cts',
    productCode: 'LMR00056'
  },
  {
    name: 'BAND IN 18K TWO TONE',
    type: 'rings',
    gender: 'female',
    category: 'vow',
    price: '$800.00',
    metalType: '18K',
    goldWeight: '4.70g',
    stoneInfo: '6 Diamonds-0.025cts',
    productCode: 'LMR00057'
  },
  {
    name: 'BAND IN 18K TWO TONE',
    type: 'rings',
    gender: 'male',
    category: 'vow',
    price: '$1,420.00',
    metalType: '18K',
    goldWeight: '7.50g',
    stoneInfo: '1 Diamond-0.102cts, 16 Diamonds-0.058cts',
    productCode: 'LMR00058'
  },
  {
    name: 'BAND IN 18K TWO TONE',
    type: 'rings',
    gender: 'female',
    category: 'vow',
    price: '$960.00',
    metalType: '18K',
    goldWeight: '4.55g',
    stoneInfo: '1 Diamond-0.061cts, 16 Diamonds-0.049cts',
    productCode: 'LMR00059'
  },
  {
    name: 'BAND IN 18K WHITE GOLD',
    type: 'rings',
    gender: 'male',
    category: 'vow',
    price: '$1,080.00',
    metalType: '18K',
    goldWeight: '7.20g',
    stoneInfo: '5 Diamonds-0.014cts',
    productCode: 'LMR00044'
  },
  {
    name: 'BAND IN 18K WHITE GOLD',
    type: 'rings',
    gender: 'female',
    category: 'vow',
    price: '$760.00',
    metalType: '18K',
    goldWeight: '4.30g',
    stoneInfo: '4 Diamonds-0.009cts',
    productCode: 'LMR00045'
  },
  {
    name: 'BAND IN 18K WHITE GOLD',
    type: 'rings',
    gender: 'male',
    category: 'vow',
    price: '$1,160.00',
    metalType: '18K',
    goldWeight: '7.10g',
    stoneInfo: '1 Diamond-0.075cts',
    productCode: 'LMR00052'
  },
  {
    name: 'BAND IN 18K WHITE GOLD',
    type: 'rings',
    gender: 'female',
    category: 'vow',
    price: '$840.00',
    metalType: '18K',
    goldWeight: '5.01g',
    stoneInfo: '1 Diamond-0.055cts',
    productCode: 'LMR00053'
  },
  {
    name: 'BAND IN 18K WHITE GOLD',
    type: 'rings',
    gender: 'male',
    category: 'vow',
    price: '$1,100.00',
    metalType: '18K',
    goldWeight: '7.40g',
    stoneInfo: '1 Princess-cut Diamond-0.030cts, 1 Diamond-0.025cts',
    productCode: 'LMR00054'
  },
  {
    name: 'BAND IN 18K WHITE GOLD',
    type: 'rings',
    gender: 'female',
    category: 'vow',
    price: '$780.00',
    metalType: '18K',
    goldWeight: '5.03g',
    stoneInfo: '1 Princess-cut Diamond-0.015cts, 1 Diamond-0.011cts',
    productCode: 'LMR00055'
  },
  {
    name: 'BAND IN 18K WHITE GOLD',
    type: 'rings',
    gender: 'female',
    category: 'vow',
    price: '$820.00',
    metalType: '18K',
    goldWeight: '4.50g',
    stoneInfo: '1 Diamond-0.037cts',
    productCode: 'LMR00061'
  },
  {
    name: 'BAND IN 18K WHITE GOLD',
    type: 'rings',
    gender: 'male',
    category: 'vow',
    price: '$1,180.00',
    metalType: '18K',
    goldWeight: '7.55g',
    stoneInfo: '1 Diamond-0.075cts',
    productCode: 'LMR00060'
  },
  {
    name: 'Birdnest',
    type: 'rings',
    category: 'heritage',
    description: 'The Goddess of Morning Dew. The solitaire diamond center sits atop a classic gold band, decorated solely with rose gold wraps and the trademark Lovemark beading on the outer band.',
    price: '$1,280.00',
    metalType: '18K',
    goldWeight: '2.52g',
    stoneInfo: '1 Diamond-0.190cts, 1 Diamond-0.007cts',
    productCode: 'LMR00007'
  },
  {
    name: 'Bloom Earrings',
    type: 'earrings',
    category: 'brilliance',
    price: '$810.00',
    metalType: '18K',
    goldWeight: '2.20g',
    stoneInfo: '2 Diamonds-0.100cts, 18 Diamonds-0.078cts',
    productCode: 'LME00102'
  },
  {
    name: 'Bloom Necklace',
    type: 'necklace',
    category: 'brilliance',
    price: '$1,840.00',
    metalType: '18K',
    goldWeight: '3.60g',
    stoneInfo: '1 Diamond-0.150cts, 2 Diamonds-0.205cts, 9 Diamonds-0.065cts',
    productCode: 'LMN00102'
  },
  {
    name: 'Bond',
    type: 'rings',
    category: 'heritage',
    description: 'The Goddess of Breeze. You pledge to each other persistently and endlessly. Show the world with the “Bond” diamond ring, which showcases a never-ending, twisted diamond band, and single diamond centre.',
    price: '$1,260.00',
    metalType: '18K',
    goldWeight: '2.63g',
    stoneInfo: '1 Diamond-0.187cts, 1 Diamond-0.007cts',
    productCode: 'LMR00002'
  },
  {
    name: 'Bridge',
    type: 'rings',
    category: 'heritage',
    description: 'The Goddess of Snow. In a perfect representation of beauty and strength, the ring showcases a hexagon shaped halo against a stark and clean band.',
    price: '$1,220.00',
    metalType: '18K',
    goldWeight: '2.48g',
    stoneInfo: '1 Diamond-0.190cts, 1 Diamond-0.007cts',
    productCode: 'LMR00001'
  },
  {
    name: 'Chain',
    type: 'rings',
    category: 'citylights',
    price: '$280.00',
    metalType: '18K',
    goldWeight: '1.62g',
    productCode: 'LMR00024'
  },
  {
    name: 'City Lights Starlight',
    type: 'rings',
    category: 'citylights',
    price: '$1,180.00',
    metalType: '18K',
    goldWeight: '3.28g',
    stoneInfo: '7 Yellow Diamonds-0.597cts',
    productCode: 'LMR00011'
  },
  {
    name: 'Classic',
    type: 'rings',
    category: 'heritage',
    description: 'The Goddess of the Moon. Inspired by the Goddess moon, This distinctive ring loves the limelight. The impact of this diamond ring’s beauty builds from the bottom up.',
    price: '$1,200.00',
    metalType: '18K',
    goldWeight: '2.42g',
    stoneInfo: '1 Diamond-0.186cts, 1 Diamond-0.007cts',
    productCode: 'LMR00006'
  },
  {
    name: 'Crown',
    type: 'rings',
    category: 'citylights',
    price: '$640.00',
    metalType: '18K',
    goldWeight: '1.80g',
    stoneInfo: '30 Diamonds-0.174cts, 5 Blue Sapphires-0.297cts',
    productCode: 'LMR00014'
  },
  {
    name: 'Curve',
    type: 'rings',
    category: 'citylights',
    price: '$620.00',
    metalType: '18K',
    goldWeight: '2.31g',
    stoneInfo: '14 Diamonds-0.182cts',
    productCode: 'LMR00015'
  },
  {
    name: 'Émera',
    type: 'rings',
    gender: 'male',
    category: 'vow',
    description: 'A clean crescent pattern lines the profile of the band allowing light to shine through the diamonds and sparkle with maximum brilliance.',
    price: '$1,020.00',
    metalType: '18K',
    goldWeight: '6.60g',
    stoneInfo: '1 Diamond-0.045cts',
    productCode: 'LMR00026'
  },
  {
    name: 'Émera',
    type: 'rings',
    gender: 'female',
    category: 'vow',
    description: 'A clean crescent pattern lines the profile of the band allowing light to shine through the diamonds and sparkle with maximum brilliance.',
    price: '$860.00',
    metalType: '18K',
    goldWeight: '5.30g',
    stoneInfo: '1 Diamond-0.033cts',
    productCode: 'LMR00027'
  },
  {
    name: 'Fairy Earrings',
    type: 'earrings',
    category: 'brilliance',
    price: '$1,940.00',
    metalType: '18K',
    goldWeight: '2.20g',
    stoneInfo: '2 Diamonds-0.170cts, 2 Diamonds-0.106cts, 8 Marquise Diamonds-0.360cts',
    productCode: 'LME00105'
  },
  {
    name: 'Fairy Necklace',
    type: 'necklace',
    category: 'brilliance',
    price: '$1,650.00',
    metalType: '18K',
    goldWeight: '2.70g',
    stoneInfo: '1 Diamond-0.150cts, 4 Marquise Diamonds-0.305cts',
    productCode: 'LMN00105'
  },
  {
    name: 'Flare Earrings',
    type: 'earrings',
    category: 'brilliance',
    price: '$780.00',
    metalType: '18K',
    goldWeight: '1.40g',
    stoneInfo: '2 Diamonds-0.17cts',
    productCode: 'LME00100'
  },
  {
    name: 'Flare Earrings in 18k White Gold Lining',
    type: 'earrings',
    category: 'brilliance',
    price: '$830.00',
    metalType: '18K',
    goldWeight: '1.70g',
    stoneInfo: '2 Diamonds-0.170cts',
    productCode: 'LME00103'
  },
  {
    name: 'Flare Earrings Surrounded with Diamonds',
    type: 'earrings',
    category: 'brilliance',
    price: '$1,180.00',
    metalType: '18K',
    goldWeight: '2.30g',
    stoneInfo: '2 Diamonds-0.180cts, 32 Diamonds-0.160cts',
    productCode: 'LME00104'
  },
  {
    name: 'Flare Necklace',
    type: 'necklace',
    category: 'brilliance',
    price: '$930.00',
    metalType: '18K',
    goldWeight: '2.20g',
    stoneInfo: '1 Diamond-0.150cts',
    productCode: 'LMN00100'
  },
  {
    name: 'Fortune Earrings',
    type: 'earrings',
    category: 'brilliance',
    price: '$840.00',
    metalType: '18K',
    goldWeight: '1.80g',
    stoneInfo: '2 Diamonds-0.17cts',
    productCode: 'LME00101'
  },
  {
    name: 'Fortune Necklace',
    type: 'necklace',
    category: 'brilliance',
    price: '$840.00',
    metalType: '18K',
    goldWeight: '1.80g',
    stoneInfo: '2 Diamonds-0.17cts',
    productCode: 'LMN00101'
  },
  {
    name: 'Galaxy',
    type: 'rings',
    category: 'citylights',
    price: '$920.00',
    metalType: '18K',
    goldWeight: '2.17g',
    stoneInfo: '41 Diamonds-0.381cts',
    productCode: 'LMR00017'
  },
  {
    name: 'HĒRA',
    type: 'rings',
    gender: 'male',
    category: 'vow',
    price: '$1,140.00',
    metalType: '18K',
    goldWeight: '7.14g',
    stoneInfo: '9 Diamonds-0.070cts',
    productCode: 'LMR00042'
  },
  {
    name: 'HĒRA',
    type: 'rings',
    gender: 'female',
    category: 'vow',
    price: '$840.00',
    metalType: '18K',
    goldWeight: '4.90g',
    stoneInfo: '22 Diamonds-0.050cts',
    productCode: 'LMR00043'
  },
  {
    name: 'Heritage Crosspath',
    type: 'rings',
    category: 'heritage',
    description: 'The Goddess of the Dawn. As interlocking as your love for one another, this band features a beautifully twisted diamond band that leads the way to a halo setting featuring small round diamond and a setting made to accommodate a Round cut diamond center. The effect is dazzling, yet delicate.',
    price: '$1,440.00',
    metalType: '18K',
    goldWeight: '2.83g',
    stoneInfo: '1 Diamond-0.185cts, 21 Diamonds-0.115cts',
    productCode: 'LMR00008'
  },
  {
    name: 'Lady Bug',
    type: 'rings',
    category: 'citylights',
    price: '$460.00',
    metalType: '18K',
    goldWeight: '1.39g',
    stoneInfo: '10 Pink Sapphires -0.104cts',
    productCode: 'LMR00023'
  },
  {
    name: 'Love Chain',
    type: 'rings',
    category: 'citylights',
    price: '$360.00',
    metalType: '18K',
    goldWeight: '1.58g',
    stoneInfo: '17 Brown Diamonds-0.063cts',
    productCode: 'LMR00020'
  },
  {
    name: 'MNÊMOSYNÊ',
    type: 'rings',
    gender: 'female',
    category: 'vow',
    description: 'Inspired by the memory god, Recreated the feeling from when you first met with the sizzling design of this wedding band.',
    price: '$840.00',
    metalType: '18K',
    goldWeight: '5.50g',
    stoneInfo: '1 Princess-cut Diamond-0.012cts, 1 Diamond-0.010cts',
    productCode: 'LMR00029'
  },
  {
    name: 'MNÊMOSYNÊ',
    type: 'rings',
    gender: 'male',
    category: 'vow',
    description: 'Inspired by the memory god, Recreated the feeling from when you first met with the sizzling design of this wedding band.',
    price: '$980.00',
    metalType: '18K',
    goldWeight: '6.30g',
    stoneInfo: '1 Princess-cut Diamond-0.025cts, 1 Diamond-0.014cts',
    productCode: 'LMR00028'
  },
  {
    name: 'Moonlight',
    type: 'rings',
    category: 'citylights',
    price: '$560.00',
    metalType: '18K',
    goldWeight: '1.43g',
    stoneInfo: '1 Diamond-0.07cts',
    productCode: 'LMR00016'
  },
  {
    name: 'Moonlight',
    type: 'rings',
    category: 'citylights',
    price: '$500.00',
    metalType: '18K',
    goldWeight: '1.24g',
    stoneInfo: '18 Yellow Diamonds-0.054cts',
    productCode: 'LMR00018'
  },
  {
    name: 'Moonlight Earrings',
    type: 'earrings',
    category: 'citylights',
    description: 'To reflect the joy, the glamorous. The beauty of the city. For every lights that shines. And reflect at a perfect time. For every moment',
    price: '$1,275.00',
    metalType: '18K',
    goldWeight: '2.00g',
    stoneInfo: '2 Diamonds-0.60cts',
    productCode: 'LME00016'
  },
  {
    name: 'Moonlight Necklace',
    type: 'necklace',
    category: 'citylights',
    price: '$600.00–$1,020.00',
    metalType: '18K Black Gold, 18K Rose Gold',
    goldWeight: '1.57g',
    length: '16, 17',
    stoneInfo: '0.200cts, 0.300cts, 0.500cts',
    productCode: 'LMN00016'
  },
  {
    name: 'Orbit Necklace',
    type: 'necklace',
    category: 'brilliance',
    price: '$1,520.00',
    metalType: '18K',
    goldWeight: '4.40g',
    stoneInfo: '1 Diamond-0.140cts, 45 Diamonds-0.220cts',
    productCode: 'LMN00104'
  },
  {
    name: 'Persian',
    type: 'rings',
    category: 'citylights',
    price: '$260.00',
    metalType: '18K',
    goldWeight: '1.32g',
    stoneInfo: '6 Yellow Diamonds-0.022cts',
    productCode: 'LMR00021'
  },
  {
    name: 'PHOIBÊ',
    type: 'rings',
    gender: 'male',
    category: 'vow',
    description: 'Like a tightly woven braid, the two of you are in it together; let this wedding ring be the metaphor for your love story. A brilliant look for the one you adore.',
    price: '$1,280.00',
    metalType: '18K',
    goldWeight: '6.64g',
    stoneInfo: '57 Diamonds-0.150cts',
    productCode: 'LMR00038'
  },
  {
    name: 'PHOIBÊ',
    type: 'rings',
    gender: 'female',
    category: 'vow',
    description: 'Like a tightly woven braid, the two of you are in it together; let this wedding ring be the metaphor for your love story. A brilliant look for the one you adore.',
    price: '$880.00',
    metalType: '18K',
    goldWeight: '4.50g',
    stoneInfo: '32 Diamonds-0.085cts',
    productCode: 'LMR00039'
  },
  {
    name: 'PROMÊTHEUS',
    type: 'rings',
    gender: 'male',
    category: 'vow',
    description: 'An exquisite symbol of your marriage commitment, this diamond wedding band is sure to please. Crafted in two-toned gold, this squared-top ring is set with a pave of round diamonds. A thoughtful symbol of your love, this majestic ring is finished with a bright polished luster.',
    price: '$1,060.00',
    metalType: '18K',
    goldWeight: '7.10g',
    stoneInfo: '3 Diamonds-0.016cts',
    productCode: 'LMR00034'
  },
  {
    name: 'PROMÊTHEUS',
    type: 'rings',
    gender: 'female',
    category: 'vow',
    description: 'An exquisite symbol of your marriage commitment, this diamond wedding band is sure to please. Crafted in two-toned gold, this squared-top ring is set with a pave of round diamonds. A thoughtful symbol of your love, this majestic ring is finished with a bright polished luster.',
    price: '$760.00',
    metalType: '18K',
    goldWeight: '4.50g',
    stoneInfo: '2 Diamonds-0.010cts',
    productCode: 'LMR00035'
  },
  {
    name: 'Ribbon',
    type: 'rings',
    category: 'citylights',
    price: '$540.00',
    metalType: '18K',
    goldWeight: '1.54g',
    stoneInfo: '11 Diamonds-0.043cts',
    productCode: 'LMR00022'
  },
  {
    name: 'Ripple',
    type: 'rings',
    category: 'heritage',
    description: 'The Goddess of Cloud. This diamond engagement ring’s twist on a single solitaire setting. An intricately woven diamond band completes the look of this remarkable ring.',
    price: '$1,260.00',
    metalType: '18K',
    goldWeight: '2.84g',
    stoneInfo: '1 Diamond-0.190cts, 1 Diamond-0.007cts',
    productCode: 'LMR00005'
  },
  {
    name: 'Rope',
    type: 'rings',
    category: 'citylights',
    price: '$280.00',
    metalType: '18K',
    goldWeight: '1.62g',
    productCode: 'LMR00025'
  },
  {
    name: 'Starlight Necklace',
    type: 'necklace',
    category: 'citylights',
    price: '$2,150.00',
    metalType: '18K',
    goldWeight: '18K',
    stoneInfo: '10 Yellow Diamonds-1.319cts',
    length: '17',
    productCode: 'LMN00011'
  },
  {
    name: 'Trine',
    type: 'rings',
    category: 'citylights',
    price: '$640.00',
    metalType: '18K',
    goldWeight: '2.86g',
    stoneInfo: '21 Diamonds-0.155cts',
    productCode: 'LMR00013'
  },
  {
    name: 'Trine',
    type: 'rings',
    category: 'citylights',
    price: '$720.00',
    metalType: '18K',
    goldWeight: '2.74g',
    stoneInfo: '21 Diamonds-0.199cts',
    productCode: 'LMR00012'
  },
  {
    name: 'Trinity Necklace',
    type: 'necklace',
    category: 'brilliance',
    price: '$1,300.00',
    metalType: '18K',
    goldWeight: '2.90g',
    stoneInfo: '1 Diamond-0.135cts, 2 Diamonds-0.100cts',
    productCode: 'LMN00103'
  },
  {
    name: 'Vintage Touch',
    type: 'rings',
    category: 'heritage',
    description: 'The Goddess of Morning. Clean, classic, cultured. A riveting, round cut diamond halo sits atop a clean shank, that lets the inner lace-like design speak for itself in this beautiful diamond ring.',
    price: '$1,320.00',
    metalType: '18K',
    goldWeight: '2.60g',
    stoneInfo: '1 Diamond-0.182cts, 1 Diamond-0.006cts',
    productCode: 'LMR00003'
  },
  {
    name: 'Zeus',
    type: 'rings',
    gender: 'female',
    category: 'vow',
    description: 'The epitome of classic elegance, this ring will take her breath away. Expertly crafted in yellow gold, this slim double scallop-edged band shimmers with a ribbon of sparkling diamonds',
    price: '$760.00',
    metalType: '18K',
    goldWeight: '4.12g',
    stoneInfo: '2 Diamonds-0.17cts',
    productCode: 'LMR00041'
  },
  {
    name: 'Zeus',
    type: 'rings',
    gender: 'male',
    category: 'vow',
    description: 'The epitome of classic elegance, this ring will take her breath away. Expertly crafted in yellow gold, this slim double scallop-edged band shimmers with a ribbon of sparkling diamonds',
    price: '$1,060.00',
    metalType: '18K',
    goldWeight: '7.10g',
    stoneInfo: '2 Diamonds-0.30cts',
    productCode: 'LMR00040'
  }
];
